// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisternegativeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registernegative() {
    // Test name: Register (negative)
    // Step # | name | target | value
    // 1 | open | https://www.greencity.social/#/greenCity | 
    driver.get("https://www.greencity.social/#/greenCity");
    // 2 | setWindowSize | 1536x824 | 
    driver.manage().window().setSize(new Dimension(1536, 824));
    // 3 | click | xpath=//span[text()='Зареєструватись '] | 
    driver.findElement(By.xpath("//span[text()=\'Зареєструватись \']")).click();
    // 4 | type | xpath=//*[@id='email'] | test@test.com
    driver.findElement(By.xpath("//*[@id=\'email\']")).sendKeys("test@test.com");
    // 5 | type | xpath=//*[@id="firstName"] | Test Register
    driver.findElement(By.xpath("//*[@id=\"firstName\"]")).sendKeys("Test Register");
    // 6 | type | xpath=//*[@id="password"] | 123
    driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("123");
    // 7 | click | xpath=//*[@id="main-content"]/h1[1] | 30000
    driver.findElement(By.xpath("//*[@id=\"main-content\"]/h1[1]")).click();
    // 8 | verifyText | xpath=//*[@id="password-err-msg"]/app-error/div |  Пароль повинен містити принаймі 8 символів без пробілів
    assertThat(driver.findElement(By.xpath("//*[@id=\"password-err-msg\"]/app-error/div")).getText(), is(" Пароль повинен містити принаймі 8 символів без пробілів"));
  }
}
