// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterpositiveTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerpositive() {
    // Test name: Register (positive)
    // Step # | name | target | value
    // 1 | open | https://www.greencity.social/#/greenCity | 
    driver.get("https://www.greencity.social/#/greenCity");
    // 2 | setWindowSize | 987x531 | 
    driver.manage().window().setSize(new Dimension(987, 531));
    // 3 | click | xpath=//span[text()='Зареєструватись '] | 
    driver.findElement(By.xpath("//span[text()=\'Зареєструватись \']")).click();
    // 4 | type | xpath=//*[@id='email'] | test_22@test.com
    driver.findElement(By.xpath("//*[@id=\'email\']")).sendKeys("test_22@test.com");
    // 5 | type | xpath=//*[@id="firstName"] | Positive test
    driver.findElement(By.xpath("//*[@id=\"firstName\"]")).sendKeys("Positive test");
    // 6 | type | id=password | 123Natat!@#
    driver.findElement(By.id("password")).sendKeys("123Natat!@#");
    // 7 | type | id=repeatPassword | 123Natat!@#
    driver.findElement(By.id("repeatPassword")).sendKeys("123Natat!@#");
    // 8 | click | //*/app-sign-up/form/button | 
    driver.findElement(By.xpath("//*/app-sign-up/form/button")).click();
    // 9 | assertElementNotPresent | //*[@id="mat-dialog-0"] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"mat-dialog-0\"]"));
      assert(elements.size() == 0);
    }
    // 10 | waitForElementPresent | //*[@id="cdk-overlay-2"]/snack-bar-container/simple-snack-bar/span | Вітання! Ви успішно зареєструвалися на сайті. Будь ласка, підтвердіть свою адресу електронної пошти.
    {
      WebDriverWait wait = new WebDriverWait(driver, NaN);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"cdk-overlay-2\"]/snack-bar-container/simple-snack-bar/span")));
    }
  }
}
